{% set name = "s3transfer" %}
{% set version = "0.18.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3760b8b7ec1315da54048b2d626276732bee4300d054d492d4e1d43e20d4ecbd

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<310]
  script_env:
    # Tests require a valid CA bundle with the path to certificates.
    - REQUESTS_CA_BUNDLE=/ssl/cacert.pem

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - botocore >=1.37.4,<2.0a.0

# Integration tests are required to validate real AWS services like S3 and SQS, which are not available in our environment.
# Error example:
#   - botocore.exceptions.NoCredentialsError: Unable to locate credentials
# Skipping integration tests:
{% set ignore_tests = " --ignore=tests/integration/" %}
# AssertionError: 'ChecksumMD5' not found in OrderedDict
{% set tests_to_skip = "test_allowed_upload_params_are_valid" %}

test:
  source_files:
    - tests
  imports:
    - s3transfer
  commands:
    - pip check
    - pytest -vv tests {{ ignore_tests }} -k "not {{ tests_to_skip }}"
  requires:
    - pip
    - pytest
    # Tests require a valid CA bundle with the path to certificates.
    # ca-certificates contains needed certificates.
    - ca-certificates

about:
  home: https://github.com/boto/s3transfer
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: An Amazon S3 Transfer Manager for Python
  description: |
    S3transfer is a Python library for managing Amazon S3 transfers.
  dev_url: https://github.com/boto/s3transfer
  doc_url: https://pypi.org/project/s3transfer

extra:
  recipe-maintainers:
    - pmlandwehr
    - proinsias
    - tkelman
    - ocefpaf
