{% set name = "s3transfer" %}
{% set version = "0.10.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5683916b4c724f799e600f41dd9e10a9ff19871bf87623cc8f491cb4f5fa0a19

build:
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv


requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - botocore >=1.33.2,<2.0a.0

test:
  imports:
    - s3transfer
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/boto/s3transfer
  license_file: LICENSE.txt
  license: Apache-2.0
  license_family: Apache
  summary: An Amazon S3 Transfer Manager for Python
  description: |
    S3transfer is a Python library for managing Amazon S3 transfers.
  dev_url: https://github.com/boto/s3transfer
  doc_url: https://pypi.org/project/s3transfer/

extra:
  recipe-maintainers:
    - pmlandwehr
    - proinsias
    - tkelman
    - ocefpaf
