{% set version = "0.5.1" %}

package:
  name: s3transfer
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/s3transfer/s3transfer-{{ version }}.tar.gz
  sha256: 69d264d3e760e569b78aaa0f22c97e955891cd22e32b10c51f784eeda4d9d10a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  host:
    - python >=3.6  # Avoid a py2k selector for the futures dependency
    - pip
    - wheel
    - setuptools
  run:
    - python >=3.6
    - botocore >=1.12.36,<2.0a.0

test:
  imports:
    - s3transfer
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/boto/s3transfer
  license_file: LICENSE.txt
  license: Apache-2.0
  license_family: Apache
  summary: An Amazon S3 Transfer Manager
  dev_url: https://github.com/boto/s3transfer
  description: |
    S3transfer is a Python library for managing Amazon S3 transfers.
  doc_url: https://pypi.python.org/pypi/s3transfer
  doc_source_url: https://github.com/boto/s3transfer/blob/develop/README.rst

extra:
  recipe-maintainers:
    - pmlandwehr
    - proinsias
    - tkelman
    - ocefpaf
