{% set name = "s3transfer" %}
{% set version = "0.13.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c3fdba22ba1bd367922f27ec8032d6a1cf5f10c934fb5d68cf60fd5a23d936cf

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - botocore >=1.37.4,<2.0a.0

# Integration tests are required to validate real AWS services like S3 and SQS, which are not available in our environment.
# Error example:
#   - botocore.exceptions.NoCredentialsError: Unable to locate credentials
# Skipping integration tests:
{% set ignore_tests = " --ignore=tests/integration/" %}

# AttributeError: Can't pickle local object 'TestBaseManager.create_pid_manager.<locals>.PIDManager'
{% set tests_to_skip = "test_can_provide_signal_handler_initializers_to_start" %}

test:
  source_files:
    - tests
  imports:
    - s3transfer
  commands:
    - pip check
    - pytest -v tests {{ ignore_tests }} -k "not ({{ tests_to_skip }})"
  requires:
    - pip
    - pytest

about:
  home: https://github.com/boto/s3transfer
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: An Amazon S3 Transfer Manager for Python
  description: |
    S3transfer is a Python library for managing Amazon S3 transfers.
  dev_url: https://github.com/boto/s3transfer
  doc_url: https://pypi.org/project/s3transfer

extra:
  recipe-maintainers:
    - pmlandwehr
    - proinsias
    - tkelman
    - ocefpaf
