{% set version = "0.2.1" %}

package:
  name: s3transfer
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/s3transfer/s3transfer-{{ version }}.tar.gz
  sha256: 6efc926738a3cd576c2a79725fed9afde92378aa5c6a957e3af010cb019fac9d

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"


requirements:
  host:
    - python
    - pip
  run:
    - python
    - botocore >=1.12.36,<2.0.0
    - futures >=2.2.0,<4.0.0  # [py2k]

test:
  imports:
    - s3transfer

about:
  home: https://github.com/boto/s3transfer
  license_file: LICENSE.txt
  license: Apache 2.0
  license_family: Apache
  summary: 'An Amazon S3 Transfer Manager'
  dev_url: https://github.com/boto/s3transfer

extra:
  recipe-maintainers:
    - pmlandwehr
    - proinsias
    - tkelman
    - ocefpaf
