{%set name = "s3transfer" %}
{%set version = "0.1.11" %}
{%set hash_type = "sha256" %}
{%set hash_val = "76f1f58f4a47e2c8afa135e2c76958806a3abbc42b721d87fd9d11409c75d979" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt


requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - botocore >=1.3.0,<2.0.0
    - futures >=2.2.0,<4.0.0  # [not py3k]

test:
  imports:
    - s3transfer

about:
  home: https://github.com/boto/s3transfer
  license: Apache 2.0
  license_file: LICENSE.txt
  license_family: Apache
  summary: 'An Amazon S3 Transfer Manager'
  description: |
    S3transfer is a Python library for managing Amazon S3 transfers.
  doc_url: https://pypi.python.org/pypi/s3transfer
  doc_source_url: https://github.com/boto/s3transfer/blob/develop/README.rst

extra:
  recipe-maintainers:
    - pmlandwehr
    - proinsias
