{% set name = "s3transfer" %}
{% set version = "0.19.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ba0309fd86be3c27dbf78cdd813c13c5e1df16e5874b99d2535ebbdfb9892993

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<310]
  script_env:
    - REQUESTS_CA_BUNDLE=$PREFIX/ssl/cacert.pem  # [not win]
    - REQUESTS_CA_BUNDLE=%PREFIX%\Library\ssl\cacert.pem  # [win]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - botocore >=1.37.4,<2.0a.0

# Integration tests are required to validate real AWS services like S3 and SQS, which are not available in our environment.
# Error example:
#   - botocore.exceptions.NoCredentialsError: Unable to locate credentials
# Skipping integration tests:
{% set ignore_tests = " --ignore=tests/integration/" %}
# AssertionError: 'ChecksumMD5' not found in OrderedDict
{% set tests_to_skip = "test_allowed_upload_params_are_valid" %}
# AssertionError: 'AnnotationDirective' not found in OrderedDict
{% set tests_to_skip = tests_to_skip +" and not test_allowed_copy_params_are_valid" %}
# - ValueError: Client s3 does not have method: list_object_annotations
{% set tests_to_skip = tests_to_skip +" and not test_mp_copy_forwards_passthrough_args_to_tag_and_annotation_calls" %}

test:
  source_files:
    - tests
  imports:
    - s3transfer
  commands:
    - pip check
    - pytest -vv tests {{ ignore_tests }} -k "not {{ tests_to_skip }}"
  requires:
    - pip
    - pytest
    # Tests require a valid CA bundle with the path to certificates.
    # ca-certificates contains needed certificates.
    - ca-certificates

about:
  home: https://github.com/boto/s3transfer
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: An Amazon S3 Transfer Manager for Python
  description: |
    S3transfer is a Python library for managing Amazon S3 transfers.
  dev_url: https://github.com/boto/s3transfer
  doc_url: https://pypi.org/project/s3transfer

extra:
  recipe-maintainers:
    - pmlandwehr
    - proinsias
    - tkelman
    - ocefpaf
