travis:
  secure:
    BINSTAR_TOKEN: YGCWWjMHJz02QiDhaTxbuo8c3yCANB1mXuSjmH+WgF8iCcHE9LEttnrJwqrw71ItvT3mVB9fIATYo86OKhwRDVdgp5DvwDUft+0zcekAhsDZ3ul3Puw/WUDikbHXs7OVWNi1iYYFQPD31EZ2kqMKZLaNfK1ryv6CzBqy4W27xiWbvJnGtZK6g2IoTG5HaLIzRXaeupFGdeoVZdIfQsZl/pczfXDcMQ56pPoHttNnfmbx9DtYg4TFe045033A2IWQIdNApGma0wS2dlGSNn7jvbZT1jQhonDI9n4VLWvY1bYKwkgrZg+ccu4sgaG6OyYrKiE+7Kj9NDEiyskeOHJxIafXgj6ZTq4AZvIdRs6XYKOj0NqQbLkVBvQjFu3v6BDCHrcKCSPDioN8KZU+wHgKxzqa7cgL3fWXZuYNKVoPLcKr5L6EaZPUjdgLDyypnxjQPu2jSfibQIqjLjJ+C90sBSm6n1GrjjGpmD/2Pfa+Fmn6BVk5fT6yfK0t2PLuzYKoDQINLsF2WieX007Mv2g9pPNPscKkLNzUiABatZTCoQWyDZeM3TD040fry1UmFYATtQqH5iqhyvHaqS/ugjC/9KOgAY4gAN3Qm7deNDkhPTAokJl8tXKDZL79o3S4YSAMgOVOQAVGEKsoixAkGCrzpWKh4SLY/lZ1uFmr7qNQo2Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
