travis:
  secure:
    BINSTAR_TOKEN: sOA32ZVFqiFNt8Eg3iUKT1E3E55JrkEkdkxOs5Iok2yDP+1r1fXX6R+OHZxRQoN9WLnIflaVk/QBJ3/oYZCgVi+cpAPQ7q6Y1mTtu2bhlQC8iAB4v+EUxeMS4391OnFrLvij0gIP70rcWHaGRHvaePQwW00KcC0yf0OxuAwgrx9uA1xDkryT6Pg6ms/cZAzmE6fiEKEU9SmWCmLRDqBwI0r4C5SrMfBBIzgjBbCkieq/UZ/U6ZydG62C3+cnUASDYuAYU44s7HogdhGAsDzyJnv5uLc5UvEuO5HmFwLeUcy8Q4WDTousxVYibzcmkQ7b1aFcDOX7W/WorNEloxdFydL0X87l+BvT+BylRYOLIzItk4lRUjaemDxgv2xP0h4Y7MlDuqwpxc4B3zU3dMglduUmnUDpXH+4+QWIVKgZQkz8p1mEEFulirDwrk4aJvv+TdXcEaiOnyMUtTqv9Ch3rLaWv3aYxhT6UBnHR5rSLmQiF+tgXpYW3cw6rydl0gsui1zD343JcfsYeyacGgIxL8iAWboiULWVupg1EoXpVkAQ973pN6xtSQhbleX5ADVOU/4tE4BhwfDg4pnFOAGXRbhhyArErR6sFEYfxqG+OVfOR14Ao5OLs6XJImJnoF+zi1NNOUG+Bwwqo4nozyMi1zOwfuIIbibTGA/cpvfdMPw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
